// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
// ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
//
// Copyright (c) Microsoft Corporation. All rights reserved


// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Code Analysis results, point to "Suppress Message", and click 
// "In Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.BindableValidator.#EmptyErrorsCollection", Justification = "ReadOnlyCollection<string> is immutable.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.Flyouts.FlyoutView.#FlyoutSizeProperty", Justification = "Static field always accessed from UI thread.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.ViewModelLocator.#AutoWireViewModelProperty", Justification = "Static field always accessed from UI thread.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "Flyout", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.MvvmAppBase.#CreateFlyoutView(System.String)", Justification = "Flyout is a standard Windows Store term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flyout", Scope = "type", Target = "Microsoft.Practices.StoreApps.Infrastructure.FlyoutService", Justification = "Flyout is a standard Windows Store term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flyout", Scope = "type", Target = "Microsoft.Practices.StoreApps.Infrastructure.Flyouts.StandardFlyoutSize", Justification = "Flyout is a standard Windows Store term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flyout", Scope = "type", Target = "Microsoft.Practices.StoreApps.Infrastructure.Flyouts.FlyoutView", Justification = "Flyout is a standard Windows Store term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "flyout", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.Flyouts.FlyoutView.#.ctor(System.Int32,Microsoft.Practices.StoreApps.Infrastructure.Interfaces.ISearchPaneService)", Justification = "Flyout is a standard Windows Store term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flyout", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.Flyouts.FlyoutView.#FlyoutSize", Justification = "Flyout is a standard Windows Store term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flyout", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.Flyouts.FlyoutView.#FlyoutSizeProperty", Justification = "Flyout is a standard Windows Store term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flyout", Scope = "type", Target = "Microsoft.Practices.StoreApps.Infrastructure.Interfaces.IFlyoutService", Justification = "Flyout is a standard Windows Store term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flyout", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.Interfaces.IFlyoutService.#FlyoutResolver", Justification = "Flyout is a standard Windows Store term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "flyout", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.Interfaces.IFlyoutService.#ShowFlyout(System.String)", Justification = "Flyout is a standard Windows Store term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flyout", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.Interfaces.IFlyoutService.#ShowFlyout(System.String)", Justification = "Flyout is a standard Windows Store term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "flyout", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.Interfaces.IFlyoutService.#ShowFlyout(System.String,System.Object,System.Action)", Justification = "Flyout is a standard Windows Store term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flyout", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.Interfaces.IFlyoutService.#ShowFlyout(System.String,System.Object,System.Action)", Justification = "Flyout is a standard Windows Store term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flyout", Scope = "type", Target = "Microsoft.Practices.StoreApps.Infrastructure.Flyouts.IFlyoutViewModel", Justification = "Flyout is a standard Windows Store term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flyout", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.Flyouts.IFlyoutViewModel.#CloseFlyout", Justification = "Flyout is a standard Windows Store term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flyout", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.MvvmAppBase.#FlyoutService", Justification = "Flyout is a standard Windows Store term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "flyout", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.MvvmAppBase.#CreateFlyoutView(System.String)", Justification = "Flyout is a standard Windows Store term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flyout", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.MvvmAppBase.#CreateFlyoutView(System.String)", Justification = "Flyout is a standard Windows Store term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "flyout", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.SettingsCharmItem.#.ctor(System.String,System.String)", Justification = "Flyout is a standard Windows Store term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flyout", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.SettingsCharmItem.#FlyoutName", Justification = "Flyout is a standard Windows Store term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "flyout", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.SettingsCharmService.#.ctor(System.Func`1<System.Collections.Generic.IList`1<Microsoft.Practices.StoreApps.Infrastructure.SettingsCharmItem>>,Microsoft.Practices.StoreApps.Infrastructure.Interfaces.IFlyoutService)", Justification = "Flyout is a standard Windows Store term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId = "0#", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.BindableBase.#SetProperty`1(!!0&,!!0,System.String)", Justification = "Template provided BindableBase requires pass by reference")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.BindableBase.#SetProperty`1(!!0&,!!0,System.String)", Justification = "CallerMemberNameAttribute requires a default parameter.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.Interfaces.IFrameFacade.#GetNavigationState()", Justification = "Matching Frame api.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Validatable", Scope = "type", Target = "Microsoft.Practices.StoreApps.Infrastructure.Interfaces.IValidatableBindableBase", Justification = "Validatable is a technical term that represents something that can be validated.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Mvvm", Scope = "type", Target = "Microsoft.Practices.StoreApps.Infrastructure.MvvmAppBase", Justification = "Mvvm is a standard term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Mvvm", Scope = "type", Target = "Microsoft.Practices.StoreApps.Infrastructure.MvvmNavigatedEventArgs", Justification = "Mvvm is a standard term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Validatable", Scope = "type", Target = "Microsoft.Practices.StoreApps.Infrastructure.ValidatableBindableBase", Justification = "Validatable is a technical term that represents something that can be validated.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.ValidatableBindableBase.#SetProperty`1(!!0&,!!0,System.String)", Justification = "CallerMemberNameAttribute requires a default parameter.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.VisualStateAwarePage.#GetSessionStateForFrame", Justification = "Nesting is required by Func<T1, T2>.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flyout", Scope = "type", Target = "Microsoft.Practices.StoreApps.Infrastructure.StandardFlyoutSize", Justification = "Flyout is a standard Windows Store App term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flyout", Scope = "type", Target = "Microsoft.Practices.StoreApps.Infrastructure.FlyoutView", Justification = "Flyout is a standard Windows Store App term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "flyout", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.FlyoutView.#.ctor(System.Int32,Microsoft.Practices.StoreApps.Infrastructure.Interfaces.ISearchPaneService)", Justification = "Flyout is a standard Windows Store App term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flyout", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.FlyoutView.#FlyoutSize", Justification = "Flyout is a standard Windows Store App term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flyout", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.FlyoutView.#FlyoutSizeProperty", Justification = "Flyout is a standard Windows Store App term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flyout", Scope = "type", Target = "Microsoft.Practices.StoreApps.Infrastructure.Interfaces.IFlyoutViewModel", Justification = "Flyout is a standard Windows Store App term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flyout", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.Interfaces.IFlyoutViewModel.#CloseFlyout", Justification = "Flyout is a standard Windows Store App term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.DelegateCommand`1.#FromAsyncHandler(System.Func`2<!0,System.Threading.Tasks.Task>)", Justification = "Factory method required for type inference.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.DelegateCommand`1.#FromAsyncHandler(System.Func`2<!0,System.Threading.Tasks.Task>,System.Func`2<!0,System.Boolean>)", Justification = "Factory method required for type inference.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.FlyoutView.#FlyoutSizeProperty", Justification = "Static field always accessed from UI thread.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.MvvmAppBase.#GetSettingsCharmItems()", Justification = "This method will potentially return a different collection on subsequent calls.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.BindableValidator.#Errors", Justification = "This class exposes the Errors IDictionary so that it can be indexed by XAML using a field name as key.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.BindableValidator.#GetAllErrors()", Justification = "This method can return a different collection of errors on subsequent calls.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.BindableValidator.#GetAllErrors()", Justification = "This class exposes the Errors IDictionary so that it can be indexed by XAML using a field name as key.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.BindableValidator.#SetAllErrors(System.Collections.Generic.IDictionary`2<System.String,System.Collections.ObjectModel.ReadOnlyCollection`1<System.String>>)", Justification = "This Set method populates the BindableValidator with data.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.Interfaces.IValidatableBindableBase.#GetAllErrors()", Justification = "This method can return a different collection of errors on subsequent calls.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.SettingsCharmService.#.ctor(System.Func`1<System.Collections.Generic.IList`1<Microsoft.Practices.StoreApps.Infrastructure.SettingsCharmItem>>,Microsoft.Practices.StoreApps.Infrastructure.Interfaces.IFlyoutService)", Justification = "The Func<T> generic is used to describe a function that returns a List<T>.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.Interfaces.IValidatableBindableBase.#GetAllErrors()", Justification = "This method returns errors in the form of a name value pair where the name refers to a field name and the value refers to the related errors.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.Interfaces.IValidatableBindableBase.#SetAllErrors(System.Collections.Generic.IDictionary`2<System.String,System.Collections.ObjectModel.ReadOnlyCollection`1<System.String>>)", Justification = "The SetAllErrors method populates object instances with the underlying error dictionary.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.AppManifestHelper.#GetApplicationId()", Justification = "This method walks through the app manifest to find the ApplicationId. This is a time intensive operation.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flyout", Scope = "type", Target = "Microsoft.Practices.StoreApps.Infrastructure.SettingsCharmFlyoutItem", Justification = "Flyout is a standard Windows Store App term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "flyout", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.SettingsCharmFlyoutItem.#.ctor(System.String,System.String)", Justification = "Flyout is a standard Windows Store App term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "flyout", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.SettingsCharmFlyoutItem.#.ctor(System.String,System.String,System.String)", Justification = "Flyout is a standard Windows Store App term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flyout", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.SettingsCharmFlyoutItem.#FlyoutName", Justification = "Flyout is a standard Windows Store App term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "flyout", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.SettingsCharmService.#.ctor(System.Func`1<System.Collections.Generic.IList`1<Microsoft.Practices.StoreApps.Infrastructure.Interfaces.ISettingsCharmItem>>,Microsoft.Practices.StoreApps.Infrastructure.Interfaces.IFlyoutService)", Justification = "Flyout is a standard Windows Store App term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.SettingsCharmService.#.ctor(System.Func`1<System.Collections.Generic.IList`1<Microsoft.Practices.StoreApps.Infrastructure.Interfaces.ISettingsCharmItem>>,Microsoft.Practices.StoreApps.Infrastructure.Interfaces.IFlyoutService)", Justification = "Necessary to describe a delegate that returns a List<SettingsCharmItem>.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "flyout", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.FlyoutView.#.ctor(System.Int32)", Justification = "Flyout is a standard Windows Store App term.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.MvvmAppBase.#GetSettingsCharmActionItems()", Justification = "This method returns a new list of items every time it is called.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "eventArgs", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.VisualStateAwarePage.#StartLayoutUpdates(System.Object,Windows.UI.Xaml.RoutedEventArgs)", Justification = "Cannot removed parameter because this method is an event handler.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "eventArgs", Scope = "member", Target = "Microsoft.Practices.StoreApps.Infrastructure.VisualStateAwarePage.#StopLayoutUpdates(System.Object,Windows.UI.Xaml.RoutedEventArgs)", Justification = "Cannot removed parameter because this method is an event handler.")]
